### ISSUE TITLE
%QUESTIONS_ANSWERS% variable is displaying questions in order of creation

### ISSUE THREAD

**Issue by sriordan9** [fpcorso/quiz_master_next#660] opened 2018-04-12 20:46 UTC
## General description
Questions are in order when user takes quiz, but when on the results page with question answers, sending emails, or exporting results questions only display in original order

## Expected behavior
Once question order has been updated and saved the order should also be correct for any post quiz results and features.

## Actual behavior
Only original question order is saved by the new question editor system

## Steps to reproduce the behavior
Create a quiz and multiple question, save the current layout. Next drag and drop the questions into a different order, save again. The new order will be saved within the "questions" tab and for the actual quiz, but for anything else only the original order is used.

**Comment by fpcorso** [comment] 2018-05-03 18:01
This issue was caused by how the answers were graded. This has been resolved in a recent commit.

**Closed by fpcorso** 2018-05-03 18:01 UTC
Labels: Bug
