### ISSUE TITLE
Adding charts with reports and results

### ISSUE THREAD

**Issue by SolutionsDEV** [fpcorso/quiz_master_next#699] opened 2018-06-24 21:03 UTC
Suggestion to add charts along with reporting and results.

Thanks

**Comment by sriordan9** [comment] 2018-07-04 19:16
@SolutionsDEV, thank you for the input! 

Could you please check out issue #692 and see if it is what you are looking for? If it is not, please provide more details for your desired feature. If it is precisely what you want (or you would like to add to it) then I'll close this issue and mention on #692 that another request has been made for it. 

Thanks again!

**Comment by fpcorso** [comment] 2018-08-19 18:43
This appears to be a duplicate of #692. Closing ticket for now.

**Closed by fpcorso** 2018-08-19 18:43 UTC
