### ISSUE TITLE
Multiple Fill-in-the-blank answers option for Fill-in-the-blank questions

### ISSUE THREAD

**Issue by gamekid88** [fpcorso/quiz_master_next#232] opened 2015-06-09 15:44 UTC
Users want to be able to have multiple fill in the blank answers for some of their fill in the blank questions. Right now if a user picks the fill in the blank question type it will work with one blank only.

**Comment by fpcorso** [comment] 2015-10-07 01:57
Duplicate of #271

**Closed by fpcorso** 2015-10-07 01:57 UTC
Labels: User Request
