### ISSUE TITLE
Required questions not working properly

### ISSUE THREAD

**Issue by markavickers** [fpcorso/quiz_master_next#292] opened 2015-09-23 17:08 UTC
I had all my questions marked as required.  Now when a user takes the survey, the only question that is actually required is the last one on the page.  

If I edit the questions, they all show NO for required.  If I change it to yes and save, it does not change.

Please help... I have users skipping critical questions.

Thanks

**Comment by fpcorso** [comment] 2015-09-23 17:48
Discussing in email now...

Possible pagination issue.

**Comment by steknef** [comment] 2016-03-16 11:50
I have the same problem...can you help me to solve this please?

**Comment by fpcorso** [comment] 2016-03-22 00:19
Duplicate of #395

**Closed by fpcorso** 2016-03-22 00:19 UTC
Labels: Bug
