### ISSUE TITLE
%QUESTIONS_ANSWERS% Text 

### ISSUE THREAD

**Issue by Greywalker1969** [fpcorso/quiz_master_next#261] opened 2015-07-04 21:26 UTC
Whatever I place in the text field is duplicated when it is presented after the quiz.

For example:

             Thank you. 

             Download Certificate 

             Thank you. 

             Download Certificate 

I have tried various ways of correcting this, but it continues to happen.

**Comment by fpcorso** [comment] 2015-07-04 21:29
The %QUESTIONS_ANSWERS% Text is shown multiple times on the results page. This variable shows the text for each question. So, in that textbox, you should use the question, comments, and answer variables to show the text for each question. If you have 10 questions, then that text will repeat 10 times.

To edit the text on the results page, you edit the content on the Results Page tab.

**Comment by fpcorso** [comment] 2015-07-04 21:35
@Greywalker1969 For further usage of the variables and creating your result page, please consult the Template Variable documentation found here: http://quizmasternext.com/quiz-master-next-template-variables/ and the Results Page documentation found here: http://quizmasternext.com/quiz-master-next-setting-up-your-results-page/

Also, please feel free to reach out to support by opening a ticket if you need assistance with setting up your quiz. You can do so here: http://quizmasternext.com/contact-us/

Since this appears to be a support related question and not a bug or issue, I am going to go ahead and close this issue here. Feel free to reach out to us via our support channels if you need assistance setting up your quiz.

**Closed by fpcorso** 2015-07-04 21:35 UTC

**Comment by Greywalker1969** [comment] 2015-07-04 21:37
Thank you for your answer.  You were most prompt.  I see now what I was doing wrong.
