### ISSUE TITLE
Pause and continue a quiz later

### ISSUE THREAD

**Issue by sriordan9** [fpcorso/quiz_master_next#654] opened 2018-04-04 16:19 UTC
## General description
User would like quiz takers to have the ability to pause their quiz and continue at a later time.

## Feature request
User email: "It will be nice if survey takers can pause a quiz and continue at a later time."

**Comment by fpcorso** [comment] 2018-04-05 00:25
Duplicate of #250

**Closed by fpcorso** 2018-04-05 00:25 UTC
