### ISSUE TITLE
Issue with outlining on internet explorer

### ISSUE THREAD

**Issue by JKetelaar** [fpcorso/quiz_master_next#290] opened 2015-09-18 07:09 UTC
Hello,
For some reason the html that gets returned doesn't contain the correct outlining for Internet Explorer

To test, fill out this form and check the results (on Internet Explorer):
http://www.nibud.nl/special_article/wat-kunt-u-doen/test-uzelf/#top_of_results

It will look a bit like this: http://i.imgur.com/2VnjtXb.png
Can you help me please?

**Comment by fpcorso** [comment] 2015-09-23 17:46
Hmmm... I just checked in IE 11 and it does push everything to the left side after submitting the quiz. Strange. I looked through the CSS of your page and nothing stands out to me. I did change overflow on one of your div for the page and then it snapped back to where it should be. Though, that doesn't solve the problem, it should help me debug it. I'll update here as soon I as discover the cause of the issue.

**Comment by JKetelaar** [comment] 2015-09-23 18:38
Thanks a bunch for your response. Looking forward to see more details!

**Comment by JKetelaar** [comment] 2015-09-29 12:58
Have you had the time yet? Looking forward to see this getting fixed as it's pretty important :+1:

**Comment by fpcorso** [comment] 2015-10-02 15:55
I have looked into this but haven't found the cause of the error yet. I am hoping to figure it out today or tomorrow hopefully.

**Comment by JKetelaar** [comment] 2015-10-04 11:12
Thanks a bunch!

**Comment by fpcorso** [comment] 2015-10-06 23:43
I have tested and debugged on Windows 7, 8, and 10 using IE 10 and 11. I tested on a local site and several testing servers. I cannot reproduce this issue on any site other than yours. But, I have looked through your CSS several times and do not see anything that would cause this.

I just went to look back at your site and the link is now a 404. Do you have an active quiz or test quiz that I can take a look at still?

**Comment by JKetelaar** [comment] 2015-10-07 12:03
Thanks for your response.
Sorry for the removal of the quiz, this is because this site is quite active

Here you go: http://www.nibud.nl/quiz/test-bent-u-klaar-voor-het-hersteladviesgesprek/

**Comment by Sjoerdje** [comment] 2015-10-21 12:34
Could it be that this is a Js error. The Ajax call seems to return a unclosed object? @fpcorso

**Comment by fpcorso** [comment] 2015-11-03 23:05
Are you still experiencing this issue @JKetelaar in the latest version of the plugin? I just tested on Windows 10 with IE 11 and on Windows 8 with IE 10 and it doesn't seem to be having the same issue as before. I changed how the results page was loaded which should have also fixed this issue.

**Closed** 2015-12-14 23:37 UTC
Labels: Bug
