### ISSUE TITLE
Ability to upload file before submitting

### ISSUE THREAD

**Issue by Dysschord** [fpcorso/quiz_master_next#283] opened 2015-09-03 20:22 UTC
I have need of users being able to upload a file before submitting their (in this case) survey. Could this be possible in a future release?

**Comment by fpcorso** [comment] 2015-09-04 17:35
Hey @dysschord! I can definitely add this to the list of requested features for you. Can you elaborate a little more on what kind of file the users will be uploading for the survey?

**Comment by Dysschord** [comment] 2015-09-04 19:01
My surveys will include a call for papers, so documents (doc, docx, rtf and
txt). Thanks!

**Comment by fpcorso** [comment] 2015-10-02 16:02
Duplicate of #242. Both are needing file upload.

**Closed by fpcorso** 2015-10-02 16:02 UTC
