### ISSUE TITLE
Pagination Bug

### ISSUE THREAD

**Issue by ilmatta88ar** [fpcorso/quiz_master_next#477] opened 2016-09-13 14:35 UTC
Please provide the following information when creating your issues:
## General description

When we try to add more then 2 questions for page, the plugin don't work. In pagination the previous button don't display the correct result
## Steps to reproduce the behavior

Just "ability navigation", and set more then **2** question for page!

**Comment by fpcorso** [comment] 2016-09-14 19:21
Hey @ilmatta88ar 

Thank you for using this plugin! Can you provide a link to a quiz that has more than 2 questions per page so that we can debug this issue?

**Comment by ilmatta88ar** [comment] 2016-09-15 07:46
Hi dear,

in this page there is an example of the surveys with pagination and bug 
active.

http://www.jwrweb.net/SEA/sondaggio-start/

When u try to go back like about 2 pages, the pagination get error, i 
think there's a problem with the counter, but i dont understand the 
script and can't fix the problem (im bad in java :-D ).

For reply the bug:

- The quiz have 6 pages, try to complete the first 5 page and then go 
back to page 2.

Quiz Setting

- Navigation with 9 section for page


Thank you, and best regards!

Il 14/09/2016 21:21, Frank Corso ha scritto:

**Comment by fpcorso** [comment] 2018-01-02 00:54
Duplicate of #467.

**Closed by fpcorso** 2018-01-02 00:54 UTC
